# Generate a Windows desktop + Start Menu launcher for Odylic Lens.
#
# Drops two .lnk shortcuts that boot the API in the background and open
# http://localhost:8765 in the default browser:
#
#   Desktop\Odylic Lens.lnk
#   AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Odylic Lens.lnk
#
# Both point at scripts\lens-start.cmd which:
#   - Starts the API as a background process (no console window)
#   - Waits for :8765 to bind
#   - Opens the default browser to localhost:8765
#
# Re-running overwrites both shortcuts with the current version.

$ErrorActionPreference = "Stop"

$LensDir = if ($env:ODYLIC_LENS_DIR) { $env:ODYLIC_LENS_DIR } else { Join-Path $env:USERPROFILE "odylic-lens" }
if (-not (Test-Path $LensDir)) {
    Write-Host "  ✗ $LensDir not found. Run install.ps1 first." -ForegroundColor Red
    exit 1
}

# 1) Write the per-install launch script — the .lnk targets call this.
$LaunchCmd = Join-Path $LensDir "scripts\lens-start.cmd"
$launchBody = @"
@echo off
REM Auto-generated by make-launcher.ps1. Edit at your own risk; re-running
REM install.ps1 (or make-launcher.ps1) will overwrite this file.
setlocal

set "LENS_DIR=%~dp0.."
pushd "%LENS_DIR%"

REM Kill any prior API instance so re-clicking the launcher doesn't pile
REM up zombies.
if exist ".run\api.pid" (
  for /f %%i in (.run\api.pid) do taskkill /PID %%i /F >nul 2>&1
)

REM Start API hidden. The wscript trick lets us launch without a console
REM window flashing on screen, which is the experience users expect from
REM a desktop shortcut. Falls back to a normal Start-Process if wscript
REM isn't available for some reason.
set "PYTHON=%LENS_DIR%\api\venv\Scripts\python.exe"
if not exist "%PYTHON%" (
  echo Odylic Lens venv not found. Run install.ps1 first.
  pause
  exit /b 1
)

if not exist ".run" mkdir .run
echo Starting Odylic Lens API...
powershell.exe -NoProfile -WindowStyle Hidden -Command ^
  "`$p = Start-Process -FilePath '%PYTHON%' -ArgumentList 'main.py' -WorkingDirectory '%LENS_DIR%\api' -WindowStyle Hidden -PassThru -RedirectStandardOutput '%LENS_DIR%\.run\api.log' -RedirectStandardError '%LENS_DIR%\.run\api.err.log'; `$p.Id | Out-File '%LENS_DIR%\.run\api.pid' -Encoding ascii -NoNewline"

REM Wait up to 10s for :8765 to bind.
set PORT=8765
for /l %%i in (1,1,40) do (
  powershell.exe -NoProfile -Command ^
    "if ((Test-NetConnection -ComputerName localhost -Port %PORT% -InformationLevel Quiet -WarningAction SilentlyContinue) -eq `$true) { exit 0 } else { Start-Sleep -Milliseconds 250; exit 1 }" >nul 2>&1
  if not errorlevel 1 goto :ready
)
:ready
start "" "http://localhost:%PORT%"
popd
endlocal
"@

Set-Content -Path $LaunchCmd -Value $launchBody -Encoding ASCII

# 2) Make / refresh an .ico for the shortcut icon.
#
# The repo ships web\public\odylic-icon.png (512px). Windows .lnk targets
# want a multi-resolution .ico. Use Python+Pillow (already installed in
# the API venv) to render one. Skip silently if anything's missing.
$IconPng    = Join-Path $LensDir "web\public\odylic-icon.png"
$IconIco    = Join-Path $LensDir "scripts\build\AppIcon.ico"
$VenvPython = Join-Path $LensDir "api\venv\Scripts\python.exe"

$canBuildIcon = (Test-Path $IconPng) -and (Test-Path $VenvPython) -and (-not (Test-Path $IconIco))
if ($canBuildIcon) {
    $iconBuildDir = Split-Path $IconIco -Parent
    if (-not (Test-Path $iconBuildDir)) {
        New-Item -ItemType Directory -Path $iconBuildDir -Force | Out-Null
    }

    # Single-quoted here-string so PowerShell doesn't try to interpolate
    # `$IconPng` / `$IconIco` (which contain backslashes that bite when
    # eval'd as Python). Use sys.argv[1..2] for the paths instead.
    $pyScript = @'
import sys
from PIL import Image
src, dst = sys.argv[1], sys.argv[2]
img = Image.open(src).convert("RGBA")
img.save(dst, format="ICO", sizes=[(16,16),(32,32),(48,48),(64,64),(128,128),(256,256)])
'@

    $tempPy = Join-Path $env:TEMP "_lens_make_ico.py"
    Set-Content -Path $tempPy -Value $pyScript -Encoding UTF8

    try {
        & $VenvPython $tempPy $IconPng $IconIco 2>$null
        if (Test-Path $IconIco) {
            Write-Host "  ✓ icon: $IconIco"
        }
    }
    catch {
        # Best-effort. Falls through to the generic shortcut icon.
    }
    finally {
        Remove-Item $tempPy -ErrorAction SilentlyContinue
    }
}

# 3) Create the .lnk shortcuts.
function New-Shortcut {
    param([string]$LinkPath, [string]$TargetPath, [string]$IconPath, [string]$WorkingDir)
    $dir = Split-Path $LinkPath -Parent
    if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }
    $WScript = New-Object -ComObject WScript.Shell
    $sc = $WScript.CreateShortcut($LinkPath)
    $sc.TargetPath = $TargetPath
    $sc.WorkingDirectory = $WorkingDir
    $sc.WindowStyle = 7   # minimized so the cmd window doesn't flash
    $sc.Description = "Odylic Lens — local Meta creative analysis"
    if ($IconPath -and (Test-Path $IconPath)) {
        $sc.IconLocation = "$IconPath,0"
    }
    $sc.Save()
}

$DesktopLnk = Join-Path ([Environment]::GetFolderPath("Desktop")) "Odylic Lens.lnk"
$StartLnk   = Join-Path ([Environment]::GetFolderPath("StartMenu")) "Programs\Odylic Lens.lnk"

New-Shortcut -LinkPath $DesktopLnk -TargetPath $LaunchCmd -IconPath $IconIco -WorkingDir $LensDir
New-Shortcut -LinkPath $StartLnk   -TargetPath $LaunchCmd -IconPath $IconIco -WorkingDir $LensDir

Write-Host "  ✓ Desktop shortcut: $DesktopLnk"
Write-Host "  ✓ Start Menu entry: $StartLnk"
Write-Host "    Double-click either, or run 'lens start' from PowerShell."
